[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "Guq3MeZzkf5CiSK7wFBm7VzKSreSiccjz7kbJpH2boW9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kimery/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
