[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "EYR8PHamGh1S1PM7d7txEDzyqfGfnchMbQ6tNHMBBsfX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
